# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentSync < Formula
  desc "Convert context and command definitions for various AI agents"
  homepage "https://github.com/uphy/agent-sync"
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/uphy/agent-sync/releases/download/v0.0.3/agent-sync_0.0.3_darwin_amd64.tar.gz"
      sha256 "533173c90d2d7f251d8d7a1d413b55dbd88a21de7c88b5113a58237f1a6937cd"

      def install
        bin.install "agent-sync"
      end
    end
    on_arm do
      url "https://github.com/uphy/agent-sync/releases/download/v0.0.3/agent-sync_0.0.3_darwin_arm64.tar.gz"
      sha256 "54fce9226c38a0d637f49fb3d049c0b6483bb8eb4a23fafc5431257a0359b4ea"

      def install
        bin.install "agent-sync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/agent-sync/releases/download/v0.0.3/agent-sync_0.0.3_linux_amd64.tar.gz"
        sha256 "2e287069871c79452203c59dd99d4a759c25ba6e661088e7ac88318e9c0a0e86"

        def install
          bin.install "agent-sync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/agent-sync/releases/download/v0.0.3/agent-sync_0.0.3_linux_arm64.tar.gz"
        sha256 "bfa8d2e8186db7a70f4afe016c622fe8049c5e492b021d74dff99c8e0bc72860"

        def install
          bin.install "agent-sync"
        end
      end
    end
  end

  test do
    system "#{bin}/agent-sync --version"
  end
end
