# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentSync < Formula
  desc "Convert context and command definitions for various AI agents"
  homepage "https://github.com/uphy/agent-sync"
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/uphy/agent-sync/releases/download/v0.0.2/agent-sync_0.0.2_darwin_amd64.tar.gz"
      sha256 "170818f35296f994a05fa0fae58928da95848f8ff5bbfd8037967050ee040432"

      def install
        bin.install "agent-sync"
      end
    end
    on_arm do
      url "https://github.com/uphy/agent-sync/releases/download/v0.0.2/agent-sync_0.0.2_darwin_arm64.tar.gz"
      sha256 "76e029e4ce23c0596c0df3046eff3568812a3ee48d7b16255f58c5173fe62654"

      def install
        bin.install "agent-sync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/agent-sync/releases/download/v0.0.2/agent-sync_0.0.2_linux_amd64.tar.gz"
        sha256 "1968747e03f86f1264d819c1129d3685e8e9655b05f34eb93a1e9c5a9252cd7c"

        def install
          bin.install "agent-sync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/agent-sync/releases/download/v0.0.2/agent-sync_0.0.2_linux_arm64.tar.gz"
        sha256 "1b9338b98484665e7433de3a12e71e8eaa021b56a3eea28d25ec650aef796c95"

        def install
          bin.install "agent-sync"
        end
      end
    end
  end

  test do
    system "#{bin}/agent-sync --version"
  end
end
