# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentDef < Formula
  desc "Convert context and command definitions for various AI agents"
  homepage "https://github.com/uphy/agent-def"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/uphy/agent-def/releases/download/v0.0.1/agent-def_0.0.1_darwin_amd64.tar.gz"
      sha256 "15485212b87355c346966a73849d64533e7afe50e17ca2c66b60b303b1dd18c2"

      def install
        bin.install "agent-def"
      end
    end
    on_arm do
      url "https://github.com/uphy/agent-def/releases/download/v0.0.1/agent-def_0.0.1_darwin_arm64.tar.gz"
      sha256 "13f105c3773ce28be2b6b5342b4abb265cc6410434b53cbe10395058a7df0467"

      def install
        bin.install "agent-def"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/agent-def/releases/download/v0.0.1/agent-def_0.0.1_linux_amd64.tar.gz"
        sha256 "96478a91e5f888082baa24a1b64feed5fe960d5f2939c2d8d315607f30e461da"

        def install
          bin.install "agent-def"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/agent-def/releases/download/v0.0.1/agent-def_0.0.1_linux_arm64.tar.gz"
        sha256 "e1880509d60d9a1cf12c5bb5fa5ad90627d519bd7fbe9785aa92b3f7fcbb1b9f"

        def install
          bin.install "agent-def"
        end
      end
    end
  end

  test do
    system "#{bin}/agent-def --version"
  end
end
