# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revealcli < Formula
  desc "CLI tool for reveal.js"
  homepage "https://github.com/uphy/go-revealjs"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/uphy/go-revealjs/releases/download/v0.0.4/revealcli-0.0.4-darwin-amd64.tar.gz"
      sha256 "1dbd9121cc987d0927913fdceff2b30e5e3652f4707f9f41308054a33e1d2c31"

      def install
        bin.install "revealcli"
      end
    end
    on_arm do
      url "https://github.com/uphy/go-revealjs/releases/download/v0.0.4/revealcli-0.0.4-darwin-arm64.tar.gz"
      sha256 "2638e886b61173c5dcdda636325032e74e734a92906988cdd50c398523c4eaed"

      def install
        bin.install "revealcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/go-revealjs/releases/download/v0.0.4/revealcli-0.0.4-linux-amd64.tar.gz"
        sha256 "9d55cd6bc1c1945b8bfbdce0af3a006257a6a75262d573fc6c711aea791e7e58"

        def install
          bin.install "revealcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/go-revealjs/releases/download/v0.0.4/revealcli-0.0.4-linux-arm64.tar.gz"
        sha256 "e50f8ffcefa1e9ec3c30124d487306f1ccefb2de2002365001a33c83b1c41a7b"

        def install
          bin.install "revealcli"
        end
      end
    end
  end
end
