# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revealcli < Formula
  desc "CLI tool for reveal.js"
  homepage "https://github.com/uphy/go-revealjs"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/uphy/go-revealjs/releases/download/v0.0.1/revealcli-0.0.1-darwin-amd64.tar.gz"
      sha256 "742f2d8949e3e1eeb2d428837a6b2be557efc422e34c6a3704961ab70371ed44"

      def install
        bin.install "revealcli"
      end
    end
    on_arm do
      url "https://github.com/uphy/go-revealjs/releases/download/v0.0.1/revealcli-0.0.1-darwin-arm64.tar.gz"
      sha256 "ef4603051b04eed54aa157f340442b6cd37b7d43438e30bebe6bffd17b9d6b41"

      def install
        bin.install "revealcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/go-revealjs/releases/download/v0.0.1/revealcli-0.0.1-linux-amd64.tar.gz"
        sha256 "f46befb660cbb29d0f74bec89436e54626a5b79dd1c331d93cfe25945f991212"

        def install
          bin.install "revealcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uphy/go-revealjs/releases/download/v0.0.1/revealcli-0.0.1-linux-arm64.tar.gz"
        sha256 "6a18a6c680366152f9d5d8a201a0b20578f616b75f67d7892f38c9e548f4e1f0"

        def install
          bin.install "revealcli"
        end
      end
    end
  end
end
